version: '2'
services:
    jhipstersampleapplication-app:
        image: jhipstersampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=jhipstersampleapplication-couchbase
            - SPRING_COUCHBASE_BUCKET_NAME=jhipsterSampleApplication
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
    jhipstersampleapplication-couchbase:
        extends:
            file: couchbase.yml
            service: jhipstersampleapplication-couchbase
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
